<?php
component('base/page-header',['title'=>'Calendário Escolar','subtitle'=>'Visualize e organize avaliações, reuniões, eventos, formações e datas importantes.']);
$canManage=\App\Core\Authorization::can(\App\Auth\Permissions::CALENDAR_MANAGE);
$typeIcons=['ASSESSMENT'=>'clipboard-check','MEETING'=>'users','COUNCIL'=>'presentation','EVENT'=>'party-popper','TRAINING'=>'graduation-cap','HOLIDAY'=>'palmtree','DEADLINE'=>'timer','OTHER'=>'calendar'];
$typeClasses=['ASSESSMENT'=>'assessment','MEETING'=>'meeting','COUNCIL'=>'council','EVENT'=>'event','TRAINING'=>'training','HOLIDAY'=>'holiday','DEADLINE'=>'deadline','OTHER'=>'other'];
$now=new DateTime(); $year=(int)$now->format('Y'); $month=(int)$now->format('n');
$monthNames=[1=>'Janeiro',2=>'Fevereiro',3=>'Março',4=>'Abril',5=>'Maio',6=>'Junho',7=>'Julho',8=>'Agosto',9=>'Setembro',10=>'Outubro',11=>'Novembro',12=>'Dezembro'];
$first=sprintf('%04d-%02d-01',$year,$month); $days=(int)date('t',strtotime($first)); $offset=(int)date('w',strtotime($first));
$byDay=[]; foreach($events as $ev){ if(empty($ev['active']))continue; $a=new DateTime((string)$ev['start_date']);$b=new DateTime((string)($ev['end_date']?:$ev['start_date']));for($d=clone $a;$d<=$b;$d->modify('+1 day')){$byDay[$d->format('Y-m-d')][]=$ev;}}
$activeCount=count(array_filter($events,fn($e)=>!empty($e['active']))); $featuredCount=count(array_filter($events,fn($e)=>!empty($e['featured'])&&!empty($e['active'])));
?>
<div class="school-calendar-page">
<?php if(!empty($calendarSuccess)): ?><div class="alert alert-success"><?=e($calendarSuccess)?></div><?php endif; ?>
<?php if(!empty($calendarError)): ?><div class="alert alert-danger"><?=e($calendarError)?></div><?php endif; ?>
<section class="calendar-page-hero card"><div><span class="calendar-page-hero__eyebrow"><i data-lucide="calendar-days"></i> Planejamento escolar</span><h2>Agenda de <?=e($monthNames[$month])?></h2><p>Tenha uma visão rápida das datas mais importantes e gerencie toda a programação da escola.</p></div><?php if($canManage): ?><a class="btn-primary" href="<?=base_url('calendario/novo')?>"><i data-lucide="calendar-plus"></i>Novo evento</a><?php endif; ?></section>
<div class="calendar-summary-grid"><article class="card"><i data-lucide="calendar-check"></i><div><strong><?=$activeCount?></strong><span>Eventos ativos</span></div></article><article class="card"><i data-lucide="star"></i><div><strong><?=$featuredCount?></strong><span>Destaques no Dashboard</span></div></article><article class="card"><i data-lucide="layers-3"></i><div><strong><?=count($types)?></strong><span>Tipos de evento</span></div></article></div>
<section class="calendar-overview card">
<header><div><span>Visão mensal</span><h3><?=e($monthNames[$month])?> de <?=$year?></h3></div><a class="btn-secondary" href="#lista-eventos"><i data-lucide="list"></i>Ver lista</a></header>
<div class="calendar-overview__week"><?php foreach(['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'] as $w):?><span><?=$w?></span><?php endforeach;?></div>
<div class="calendar-overview__grid"><?php for($i=0;$i<$offset;$i++):?><div class="calendar-overview__day is-empty"></div><?php endfor;?><?php for($day=1;$day<=$days;$day++):$date=sprintf('%04d-%02d-%02d',$year,$month,$day);$dayEvents=$byDay[$date]??[];$today=$date===date('Y-m-d');?><div class="calendar-overview__day <?=$today?'is-today':''?> <?=!empty($dayEvents)?'has-events':''?>"><span class="calendar-overview__number"><?=$day?></span><div class="calendar-overview__events"><?php foreach(array_slice($dayEvents,0,3) as $ev):$t=(string)$ev['type'];?><a href="#evento-<?=(int)$ev['id']?>" class="calendar-overview__event type-<?=e($typeClasses[$t]??'other')?> <?=!empty($ev['featured'])?'is-featured':''?>" title="<?=e((string)$ev['title'])?>"><?=!empty($ev['featured'])?'<i data-lucide="star"></i>':''?><span><?=e((string)$ev['title'])?></span></a><?php endforeach;?><?php if(count($dayEvents)>3):?><small>+<?=count($dayEvents)-3?> evento(s)</small><?php endif;?></div></div><?php endfor;?></div>
<div class="calendar-type-legend"><?php foreach($types as $key=>$label):?><span class="type-<?=e($typeClasses[$key]??'other')?>"><i></i><?=e($label)?></span><?php endforeach;?></div>
</section>
<section id="lista-eventos" class="calendar-events-panel card"><div class="school-calendar-toolbar"><div><span>Programação cadastrada</span><h3><?=count($events)?> evento(s)</h3></div><label class="calendar-search"><i data-lucide="search"></i><input id="calendar-event-search" type="search" placeholder="Pesquisar evento..."></label></div>
<div class="school-calendar-list" id="calendar-event-list">
<?php if(empty($events)): ?><div class="empty-state"><i data-lucide="calendar-days"></i><h3>Nenhum evento cadastrado</h3><p>Cadastre a primeira data importante da escola.</p></div><?php endif; ?>
<?php foreach($events as $event): $type=(string)$event['type'];$startTime=substr((string)($event['start_time']??''),0,5);$endTime=substr((string)($event['end_time']??''),0,5);$startDate=(string)$event['start_date'];$endDate=(string)($event['end_date']?:$event['start_date']);$sameDay=$startDate===$endDate; ?>
<article id="evento-<?=(int)$event['id']?>" class="school-event-row type-<?=e($typeClasses[$type]??'other')?> <?=empty($event['active'])?'is-inactive':''?> <?=!empty($event['featured'])?'is-featured':''?>" data-search="<?=e(mb_strtolower((string)$event['title'].' '.(string)($event['description']??'').' '.($types[$type]??'')))?>">
<div class="school-event-period"><div class="school-event-period__point"><small>Início</small><strong><?=date('d/m/Y',strtotime($startDate))?></strong><?php if(empty($event['all_day'])&&$startTime!==''):?><span><?=$startTime?></span><?php endif;?></div><?php if(!$sameDay||(!empty($endTime)&&$endTime!==$startTime)):?><i data-lucide="arrow-right"></i><div class="school-event-period__point"><small>Fim</small><strong><?=date('d/m/Y',strtotime($endDate))?></strong><?php if(empty($event['all_day'])&&$endTime!==''):?><span><?=$endTime?></span><?php endif;?></div><?php endif;?></div>
<div class="school-event-icon"><i data-lucide="<?=e($typeIcons[$type]??'calendar')?>"></i></div>
<div class="school-event-content"><div class="school-event-badges"><span><?=e($types[$type]??'Outro')?></span><?php if(!empty($event['featured'])):?><span class="featured"><i data-lucide="star"></i>Destaque</span><?php endif;?><?php if(empty($event['active'])):?><span>Inativo</span><?php endif;?></div><h3><?=e((string)$event['title'])?></h3><?php if(!empty($event['description'])):?><p><?=e((string)$event['description'])?></p><?php endif;?><small><span><i data-lucide="calendar-range"></i><?=e(date('d/m/Y',strtotime($startDate)).(!$sameDay?' até '.date('d/m/Y',strtotime($endDate)):''))?></span><span><i data-lucide="clock"></i><?=!empty($event['all_day'])?'Dia inteiro':e(($startTime!==''?$startTime:'--:--').($endTime!==''?' às '.$endTime:''))?></span><?php if(!empty($event['location'])): ?><span><i data-lucide="map-pin"></i><?=e((string)$event['location'])?></span><?php endif;?></small></div>
<?php if($canManage): ?><div class="school-event-actions"><a class="icon-button" href="<?=base_url('calendario/editar?id='.(int)$event['id'])?>" title="Editar"><i data-lucide="pencil"></i></a><form method="post" action="<?=base_url('calendario/excluir')?>" onsubmit="return confirm('Excluir este evento?')"><input type="hidden" name="id" value="<?=(int)$event['id']?>"><button class="icon-button danger" type="submit" title="Excluir"><i data-lucide="trash-2"></i></button></form></div><?php endif; ?>
</article><?php endforeach; ?></div></section></div>
<script>document.getElementById('calendar-event-search')?.addEventListener('input',function(){const q=this.value.toLocaleLowerCase('pt-BR').trim();document.querySelectorAll('#calendar-event-list .school-event-row').forEach(el=>el.hidden=q!==''&&!el.dataset.search.includes(q));});</script>
